package com.stackpointer.lists.ui.theme

import androidx.compose.ui.graphics.Color

// Tokens copied verbatim from the Claude Design spec ("Lists - M3 Expressive"),
// seed color #A03E28. Roles not explicitly specified by the design (secondary,
// surfaceVariant, inverse*, surfaceTint, scrim, surfaceBright/Dim, onError) are
// filled with values consistent with standard Material 3 tonal conventions.

// Light scheme
val LightSurface = Color(0xFFFFF8F6)
val LightOnSurface = Color(0xFF231917)
val LightOnSurfaceVariant = Color(0xFF53433F)
val LightOutline = Color(0xFF85736E)
val LightOutlineVariant = Color(0xFFD8C2BC)
val LightPrimary = Color(0xFFA03E28)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFDBD0)
val LightOnPrimaryContainer = Color(0xFF3A0B01)
val LightSecondary = Color(0xFF7D5847)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFF8DED6)
val LightOnSecondaryContainer = Color(0xFF2C1610)
val LightTertiary = Color(0xFF006A60)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFF9EF2E4)
val LightOnTertiaryContainer = Color(0xFF00201C)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFFFF1ED)
val LightSurfaceContainer = Color(0xFFFCEAE5)
val LightSurfaceContainerHigh = Color(0xFFF6E4E0)
val LightSurfaceContainerHighest = Color(0xFFF0DFDA)
val LightSurfaceBright = Color(0xFFFFF8F6)
val LightSurfaceDim = Color(0xFFE7D6D1)
val LightScrim = Color(0xFF000000)

// Dark scheme
val DarkSurface = Color(0xFF1A1110)
val DarkOnSurface = Color(0xFFF0DFDA)
val DarkOnSurfaceVariant = Color(0xFFD8C2BC)
val DarkOutline = Color(0xFFA08C87)
val DarkOutlineVariant = Color(0xFF53433F)
val DarkPrimary = Color(0xFFFFB5A0)
val DarkOnPrimary = Color(0xFF5D1800)
val DarkPrimaryContainer = Color(0xFF7D2A10)
val DarkOnPrimaryContainer = Color(0xFFFFDBD0)
val DarkSecondary = Color(0xFFECC0B0)
val DarkOnSecondary = Color(0xFF3F2D25)
val DarkSecondaryContainer = Color(0xFF5D4037)
val DarkOnSecondaryContainer = Color(0xFFFFDBD0)
val DarkTertiary = Color(0xFF82D5C8)
val DarkOnTertiary = Color(0xFF003731)
val DarkTertiaryContainer = Color(0xFF00504A)
val DarkOnTertiaryContainer = Color(0xFF9EF2E4)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkSurfaceContainerLowest = Color(0xFF140C0B)
val DarkSurfaceContainerLow = Color(0xFF231917)
val DarkSurfaceContainer = Color(0xFF271D1B)
val DarkSurfaceContainerHigh = Color(0xFF322825)
val DarkSurfaceContainerHighest = Color(0xFF3D3230)
val DarkSurfaceBright = Color(0xFF423734)
val DarkSurfaceDim = Color(0xFF1A1110)
val DarkScrim = Color(0xFF000000)
